import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../../globals.css";
import NavBar from "@/ui/navtopBar/NavBar";

const inter = Inter({ subsets: ["latin"] });
import FooterBar from "@/ui/Footer/FooterBar";
import { Suspense } from "react";
import Main from "@/ui/Main/Main";
import Queue from "@/ui/Queue/Queue";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className=" h-full bg-[#111111] text-white">
      <body
        className={`${inter.className} overflow-hidden relative h-full   flex flex-col`}
        style={{}}
      >
        <NavBar />
        <div className="scr flex flex-1 overflow-hidden relative">
          <Suspense
            fallback={
              <div className="px-1 h-full flex-1 overflow-y-scroll bg-green-700"></div>
            }
          >
            <Main>
              {children}
              <h1>this is footer bar</h1>
              <h1>made by github Lorem ipsum dolor sit amet,</h1>
            </Main>

            <Queue />
          </Suspense>
        </div>
        <Suspense
          fallback={
            <div className="w-full  flex   items-center  h-[70px] bg-red-950"></div>
          }
        >
          <FooterBar />
        </Suspense>
      </body>
    </html>
  );
}
