import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../../globals.css";
import NavBar from "@/ui/navtopBar/NavBar";

const inter = Inter({ subsets: ["latin"] });
import FooterBar from "@/ui/Footer/FooterBar";
import NavSideBar from "@/ui/navtopBar/NavSideBar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} relative `} style={{}}>
        <NavBar />
        <div className="scr">
          <main className="px-1 sm:pl-[70px] pt-[5px] pb-[70px]">
            {children}
            <h1>this is footer bar</h1>
            <h1>made by github Lorem ipsum dolor sit amet,</h1>
          </main>
        </div>

        <footer className="fixed z-30  bottom-0 w-full bg-yellow-400 flex  items-center  h-[50px]">
          <FooterBar />
        </footer>
      </body>
    </html>
  );
}
